sudo: false
language: node_js

node_js:
  - "4"
  - "5"
  - "6"

cache:
  yarn: true
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules

install: make install
script: make ci-test
